In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, roc_auc_score, roc_curve, auc,precision_score, recall_score, f1_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
import xgboost as xgb
from sklearn.neighbors import KNeighborsClassifier

In [2]:
df = pd.read_csv(r'E:\credit_risk_modeling\data\final_dataset.csv')
df.head()

,PROSPECTID,Total_TL,Tot_Closed_TL,Tot_Active_TL,Total_TL_opened_L6M,Tot_TL_closed_L6M,pct_tl_open_L6M,pct_tl_closed_L6M,pct_active_tl,pct_closed_tl,...,last_prod_enq2_CC,last_prod_enq2_ConsumerLoan,last_prod_enq2_HL,last_prod_enq2_PL,last_prod_enq2_others,first_prod_enq2_CC,first_prod_enq2_ConsumerLoan,first_prod_enq2_HL,first_prod_enq2_PL,first_prod_enq2_others
0,1,5,4,1,0,0,0.000,0.0,0.200,0.800,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1,2,1,0,1,0,0,0.000,0.0,1.000,0.000,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,3,8,0,8,1,0,0.125,0.0,1.000,0.000,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,5,3,2,1,0,0,0.000,0.0,0.333,0.667,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,6,6,5,1,0,0,0.000,0.0,0.167,0.833,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [4]:
df["Credit_Score"].value_counts()

Credit_Score
678    1108
679    1053
682    1041
680    1021
677    1006
       ...
499       1
489       1
801       1
469       1
513       1
Name: count, Length: 244, dtype: int64

In [ ]:
cvbnm,.

In [ ]:
X=df.drop('Approved_Flag', axis=1)
y=df['Approved_Flag']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=42)

In [ ]:
df_new=df[[ 
    'pct_tl_open_L6M',
    'pct_tl_closed_L6M',
    'pct_active_tl',
    'pct_closed_tl',
    'Total_TL_opened_L12M',
    'Tot_TL_closed_L12M',
    'pct_tl_open_L12M',
    'pct_tl_closed_L12M',
    'Tot_Missed_Pmnt',
    'CC_TL',
    'Home_TL',
    'PL_TL',
    'Secured_TL',
    'Unsecured_TL',
    'Other_TL',
    'Age_Oldest_TL',
    'Age_Newest_TL'
]]

In [ ]:
df_new.describe()

,pct_tl_open_L6M,pct_tl_closed_L6M,pct_active_tl,pct_closed_tl,Total_TL_opened_L12M,Tot_TL_closed_L12M,pct_tl_open_L12M,pct_tl_closed_L12M,Tot_Missed_Pmnt,CC_TL,Home_TL,PL_TL,Secured_TL,Unsecured_TL,Other_TL,Age_Oldest_TL,Age_Newest_TL
count,42064.000000,42064.000000,42064.000000,42064.000000,42064.000000,42064.000000,42064.000000,42064.000000,42064.000000,42064.000000,42064.000000,42064.000000,42064.000000,42064.000000,42064.000000,42064.000000,42064.000000
mean,0.179032,0.097783,0.577452,0.422548,1.672142,0.825504,0.401271,0.160365,0.525746,0.145921,0.076241,0.328000,2.921334,2.341646,1.116489,46.498074,13.970046
std,0.278043,0.210957,0.366110,0.366110,2.249543,1.537208,0.381266,0.258831,1.106442,0.549314,0.358582,0.916368,6.379764,3.405397,2.486801,42.109230,18.835191
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.286000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.000000,4.000000
50%,0.000000,0.000000,0.545000,0.455000,1.000000,0.000000,0.333000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,34.000000,7.000000
75%,0.333000,0.100000,1.000000,0.714000,2.000000,1.000000,0.714000,0.250000,1.000000,0.000000,0.000000,0.000000,3.000000,3.000000,1.000000,65.000000,16.000000
max,1.000000,1.000000,1.000000,1.000000,34.000000,33.000000,1.000000,1.000000,34.000000,27.000000,10.000000,29.000000,235.000000,55.000000,80.000000,385.000000,359.000000

In [ ]:
from sklearn.preprocessing import RobustScaler  

num_cols = [
    'pct_tl_open_L6M',
    'pct_tl_closed_L6M',
    'pct_active_tl',
    'pct_closed_tl',
    'Total_TL_opened_L12M',
    'Tot_TL_closed_L12M',
    'pct_tl_open_L12M',
    'pct_tl_closed_L12M',
    'Tot_Missed_Pmnt',
    'CC_TL',
    'Home_TL',
    'PL_TL',
    'Secured_TL',
    'Unsecured_TL',
    'Other_TL',
    'Age_Oldest_TL',
    'Age_Newest_TL'
]

scaler = RobustScaler()

X_train_scaled = scaler.fit_transform(X_train[num_cols])
X_test_scaled = scaler.transform(X_test[num_cols])

# Logisctic regression

In [ ]:
logreg = LogisticRegression(class_weight='balanced',random_state=42)
logreg.fit(X_train_scaled, y_train)


y_pred_train = logreg.predict(X_train_scaled)
print("Training Report:")
print(classification_report(y_train, y_pred_train))



y_pred_test = logreg.predict(X_test_scaled)
print("Test Report:")
print(classification_report(y_test, y_pred_test))

Training Report:
              precision    recall  f1-score   support

           0       0.44      0.80      0.57      3894
           1       0.72      0.46      0.56     20407
           2       0.20      0.14      0.16      5115
           3       0.23      0.53      0.32      4235

    accuracy                           0.46     33651
   macro avg       0.40      0.48      0.40     33651
weighted avg       0.54      0.46      0.47     33651

Test Report:
              precision    recall  f1-score   support

           0       0.46      0.79      0.58      1014
           1       0.70      0.46      0.56      5045
           2       0.19      0.13      0.16      1325
           3       0.22      0.54      0.32      1029

    accuracy                           0.46      8413
   macro avg       0.39      0.48      0.40      8413
weighted avg       0.53      0.46      0.47      8413

# Knn clasifier

In [ ]:
kc = KNeighborsClassifier(n_neighbors=5)
kc.fit(X_train_scaled, y_train)

y_pred_train_kc = kc.predict(X_train_scaled)
print("Training Report:")
print(classification_report(y_train, y_pred_train_kc))
print()
y_pred_test_kc = kc.predict(X_test_scaled)
print("Test Report:")
print(classification_report(y_test, y_pred_test_kc))

Training Report:
              precision    recall  f1-score   support

           0       0.67      0.63      0.65      3894
           1       0.70      0.92      0.79     20407
           2       0.48      0.18      0.26      5115
           3       0.63      0.19      0.29      4235

    accuracy                           0.68     33651
   macro avg       0.62      0.48      0.50     33651
weighted avg       0.65      0.68      0.63     33651


Test Report:
              precision    recall  f1-score   support

           0       0.56      0.47      0.51      1014
           1       0.64      0.85      0.73      5045
           2       0.19      0.07      0.10      1325
           3       0.29      0.10      0.14      1029

    accuracy                           0.59      8413
   macro avg       0.42      0.37      0.37      8413
weighted avg       0.52      0.59      0.53      8413

# Decision tree classifier

In [ ]:
dc=DecisionTreeClassifier(random_state=42)
dc.fit(X_train, y_train)
y_pred_train_dc = dc.predict(X_train)
print("Training Report:")
print(classification_report(y_train, y_pred_train_dc))
print()
y_pred_test_dc = dc.predict(X_test)
print("Test Report:")
print(classification_report(y_test, y_pred_test_dc))

Training Report:
              precision    recall  f1-score   support

           0       0.99      1.00      0.99      3894
           1       0.96      1.00      0.98     20407
           2       0.97      0.89      0.93      5115
           3       0.99      0.91      0.95      4235

    accuracy                           0.97     33651
   macro avg       0.98      0.95      0.96     33651
weighted avg       0.97      0.97      0.97     33651


Test Report:
              precision    recall  f1-score   support

           0       0.49      0.46      0.48      1014
           1       0.65      0.66      0.66      5045
           2       0.20      0.19      0.20      1325
           3       0.25      0.25      0.25      1029

    accuracy                           0.51      8413
   macro avg       0.40      0.39      0.39      8413
weighted avg       0.51      0.51      0.51      8413

# Random forest

In [ ]:
rc= RandomForestClassifier(random_state=42)
rc.fit(X_train, y_train)
y_pred_train_rf = rc.predict(X_train)
print("Training Report:")
print(classification_report(y_train, y_pred_train_rf))
print()
y_pred_test_rf = rc.predict(X_test)
print("Test Report:")
print(classification_report(y_test, y_pred_test_rf))

Training Report:
              precision    recall  f1-score   support

           0       1.00      0.99      0.99      3894
           1       0.96      0.99      0.98     20407
           2       0.96      0.89      0.93      5115
           3       0.97      0.93      0.95      4235

    accuracy                           0.97     33651
   macro avg       0.97      0.95      0.96     33651
weighted avg       0.97      0.97      0.97     33651


Test Report:
              precision    recall  f1-score   support

           0       0.65      0.51      0.57      1014
           1       0.66      0.88      0.75      5045
           2       0.25      0.08      0.12      1325
           3       0.37      0.16      0.22      1029

    accuracy                           0.62      8413
   macro avg       0.48      0.41      0.42      8413
weighted avg       0.56      0.62      0.57      8413

# Xgboost

In [ ]:
xgb_clf = xgb.XGBClassifier(random_state=42)
xgb_clf.fit(X_train, y_train)
y_pred_train_xgb = xgb_clf.predict(X_train)
print("Training Report:")
print(classification_report(y_train, y_pred_train_xgb))
print()
y_pred_test_xgb = xgb_clf.predict(X_test)
print("Test Report:")
print(classification_report(y_test, y_pred_test_xgb))

Training Report:
              precision    recall  f1-score   support

           0       0.84      0.69      0.76      3894
           1       0.71      0.97      0.82     20407
           2       0.77      0.14      0.24      5115
           3       0.77      0.35      0.48      4235

    accuracy                           0.73     33651
   macro avg       0.77      0.54      0.58     33651
weighted avg       0.74      0.73      0.68     33651


Test Report:
              precision    recall  f1-score   support

           0       0.67      0.52      0.59      1014
           1       0.66      0.92      0.77      5045
           2       0.31      0.04      0.07      1325
           3       0.44      0.17      0.25      1029

    accuracy                           0.64      8413
   macro avg       0.52      0.41      0.42      8413
weighted avg       0.58      0.64      0.57      8413

In [ ]:
from sklearn.utils.class_weight import compute_class_weight


classes = np.unique(y_train)

weights = compute_class_weight(
    class_weight='balanced',
    classes=classes,
    y=y_train
)

class_weights = dict(zip(classes, weights))

print(class_weights)

{np.int64(0): np.float64(2.1604391371340523), np.int64(1): np.float64(0.41224824815014455), np.int64(2): np.float64(1.6447214076246335), np.int64(3): np.float64(1.9864817001180637)}

In [ ]:
sample_weights = y_train.map(class_weights)

In [ ]:


xgb_clf = xgb.XGBClassifier(
    random_state=42,
    objective='multi:softprob', 
    eval_metric='mlogloss'
)

xgb_clf.fit(X_train, y_train, sample_weight=sample_weights)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='mlogloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, ...)

In [ ]:
# Train
print("XGBoost with Class Weights:")
y_pred_train_xgb = xgb_clf.predict(X_train)
print("Training Report:")
print(classification_report(y_train, y_pred_train_xgb))

print()

# Test
y_pred_test_xgb = xgb_clf.predict(X_test)
print("Test Report:")
print(classification_report(y_test, y_pred_test_xgb))

XGBoost with Class Weights:
Training Report:
              precision    recall  f1-score   support

           0       0.55      0.95      0.69      3894
           1       0.88      0.55      0.68     20407
           2       0.42      0.58      0.48      5115
           3       0.44      0.73      0.55      4235

    accuracy                           0.62     33651
   macro avg       0.57      0.70      0.60     33651
weighted avg       0.72      0.62      0.63     33651


Test Report:
              precision    recall  f1-score   support

           0       0.46      0.81      0.58      1014
           1       0.75      0.47      0.58      5045
           2       0.25      0.31      0.28      1325
           3       0.27      0.47      0.35      1029

    accuracy                           0.49      8413
   macro avg       0.43      0.52      0.45      8413
weighted avg       0.58      0.49      0.50      8413

# treat imbalance data

# Under  sampling techinques

In [ ]:
from collections import Counter
from imblearn.under_sampling import RandomUnderSampler
rus=RandomUnderSampler(random_state=42)
X_train_resampled, y_train_resampled = rus.fit_resample(X_train, y_train)
print(Counter(y_train_resampled))
print(Counter(y_train))

Counter({0: 3894, 1: 3894, 2: 3894, 3: 3894})
Counter({1: 20407, 2: 5115, 3: 4235, 0: 3894})

In [ ]:
from imblearn.under_sampling import RandomUnderSampler
rus=RandomUnderSampler(random_state=42)
X_train_resampled, y_train_resampled = rus.fit_resample(X_train, y_train)
print(Counter(y_train_resampled))
print(Counter(y_train))
xgb_im = xgb.XGBClassifier(random_state=42)
xgb_im.fit(X_train_resampled, y_train_resampled)

# Training (optional, but not very useful)
y_pred_train = xgb_im.predict(X_train_resampled)
print("Training Report:")
print(classification_report(y_train_resampled, y_pred_train))

# Test (this is what matters)
y_pred_test = xgb_im.predict(X_test)
print("\nTest Report:")
print(classification_report(y_test, y_pred_test))

In [ ]:
xgb_im = xgb.XGBClassifier(random_state=42)
xgb_im.fit(X_train_resampled, y_train_resampled)

# Training (optional, but not very useful)
y_pred_train = xgb_im.predict(X_train_resampled)
print("Training Report:")
print(classification_report(y_train_resampled, y_pred_train))

# Test (this is what matters)
y_pred_test = xgb_im.predict(X_test)
print("\nTest Report:")
print(classification_report(y_test, y_pred_test))

Training Report:
              precision    recall  f1-score   support

           0       0.86      0.95      0.90      3894
           1       0.70      0.66      0.68      3894
           2       0.68      0.63      0.65      3894
           3       0.73      0.75      0.74      3894

    accuracy                           0.74     15576
   macro avg       0.74      0.74      0.74     15576
weighted avg       0.74      0.74      0.74     15576


Test Report:
              precision    recall  f1-score   support

           0       0.44      0.84      0.58      1014
           1       0.76      0.39      0.52      5045
           2       0.22      0.32      0.26      1325
           3       0.25      0.48      0.33      1029

    accuracy                           0.45      8413
   macro avg       0.42      0.51      0.42      8413
weighted avg       0.58      0.45      0.46      8413

# Tomek link

In [ ]:
from imblearn.under_sampling import TomekLinks

tl = TomekLinks()

X_train_resampled1, y_train_resampled1 = tl.fit_resample(X_train, y_train)
print("Before resampling:", Counter(y_train))
print("After resampling:", Counter(y_train_resampled1))

Before resampling: Counter({1: 20407, 2: 5115, 3: 4235, 0: 3894})
After resampling: Counter({1: 18070, 0: 3894, 2: 3795, 3: 3198})

In [ ]:
xgtom=xgb.XGBClassifier(random_state=42)
xgtom.fit(X_train_resampled1, y_train_resampled1)
print("Training Report:")
y_pred_train_xgtom = xgtom.predict(X_train_resampled1)
print(classification_report(y_train_resampled1, y_pred_train_xgtom))
print()
y_pred_test_xgtom = xgtom.predict(X_test)
print("Test Report:")
print(classification_report(y_test, y_pred_test_xgtom))

Training Report:
              precision    recall  f1-score   support

           0       0.88      0.75      0.81      3894
           1       0.75      0.97      0.85     18070
           2       0.82      0.17      0.28      3795
           3       0.81      0.38      0.52      3198

    accuracy                           0.77     28957
   macro avg       0.82      0.57      0.61     28957
weighted avg       0.78      0.77      0.73     28957


Test Report:
              precision    recall  f1-score   support

           0       0.65      0.59      0.62      1014
           1       0.66      0.91      0.77      5045
           2       0.30      0.04      0.06      1325
           3       0.45      0.17      0.25      1029

    accuracy                           0.64      8413
   macro avg       0.52      0.43      0.42      8413
weighted avg       0.58      0.64      0.57      8413

# logistic

In [ ]:
X_train_resampled2, y_train_resampled2 = tl.fit_resample(X_train_scaled, y_train)
print("Before resampling:", Counter(y_train))
print("After resampling:", Counter(y_train_resampled2))

Before resampling: Counter({1: 20407, 2: 5115, 3: 4235, 0: 3894})
After resampling: Counter({1: 17939, 0: 3894, 2: 3782, 3: 3113})

In [ ]:
log2 = LogisticRegression(random_state=42)
log2.fit(X_train_resampled2, y_train_resampled2)
print("Training Report:")
y_pred_train_log2 = log2.predict(X_train_resampled2)
print(classification_report(y_train_resampled2, y_pred_train_log2))
print()
y_pred_test_log2 = log2.predict(X_test_scaled)
print("Test Report:")
print(classification_report(y_test, y_pred_test_log2))

Training Report:
              precision    recall  f1-score   support

           0       0.72      0.51      0.60      3894
           1       0.67      0.96      0.79     17939
           2       0.00      0.00      0.00      3782
           3       0.57      0.04      0.08      3113

    accuracy                           0.67     28728
   macro avg       0.49      0.38      0.37     28728
weighted avg       0.58      0.67      0.58     28728


Test Report:
              precision    recall  f1-score   support

           0       0.65      0.51      0.57      1014
           1       0.63      0.95      0.76      5045
           2       0.00      0.00      0.00      1325
           3       0.49      0.04      0.07      1029

    accuracy                           0.63      8413
   macro avg       0.44      0.37      0.35      8413
weighted avg       0.52      0.63      0.53      8413

e:\credit_risk_modeling\shani67\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
e:\credit_risk_modeling\shani67\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
e:\credit_risk_modeling\shani67\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
e:\credit_risk_modeling\shani67\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
e:\credit_risk_modeling\shani67\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
e:\credit_risk_modeling\shani67\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [ ]:
from imblearn.under_sampling import EditedNearestNeighbours
enn = EditedNearestNeighbours()
X_train_resampled3, y_train_resampled3 = enn.fit_resample(X_train,
y_train)
print("Before resampling:", Counter(y_train))
print("After resampling:", Counter(y_train_resampled3))

Before resampling: Counter({1: 20407, 2: 5115, 3: 4235, 0: 3894})
After resampling: Counter({1: 7077, 0: 3894, 3: 118, 2: 87})

# overSmapling

In [ ]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=42)
X_train_resampled4, y_train_resampled4 = smote.fit_resample(X_train, y_train)
print("Before resampling:", Counter(y_train))
print("After resampling:", Counter(y_train_resampled4))

Before resampling: Counter({1: 20407, 2: 5115, 3: 4235, 0: 3894})
After resampling: Counter({0: 20407, 1: 20407, 2: 20407, 3: 20407})

In [ ]:
rc= RandomForestClassifier(random_state=42)
rc.fit(X_train_resampled4, y_train_resampled4)
y_pred_train_rf = rc.predict(X_train_resampled4)
print("Training Report:")
print(classification_report(y_train_resampled4, y_pred_train_rf))
print()
y_pred_test_rf = rc.predict(X_test)
print("Test Report:")
print(classification_report(y_test, y_pred_test_rf))

Training Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     20407
           1       0.97      0.96      0.97     20407
           2       0.97      0.97      0.97     20407
           3       0.98      0.98      0.98     20407

    accuracy                           0.98     81628
   macro avg       0.98      0.98      0.98     81628
weighted avg       0.98      0.98      0.98     81628


Test Report:
              precision    recall  f1-score   support

           0       0.60      0.60      0.60      1014
           1       0.67      0.80      0.73      5045
           2       0.26      0.13      0.18      1325
           3       0.32      0.22      0.26      1029

    accuracy                           0.60      8413
   macro avg       0.46      0.44      0.44      8413
weighted avg       0.55      0.60      0.57      8413

In [ ]:

print("SMOTE Resampling:")
xgb_sm= xgb.XGBClassifier(random_state=42)
xgb_sm.fit(X_train_resampled4, y_train_resampled4)
print("Training Report:")
y_pred_train_xgb_sm = xgb_sm.predict(X_train_resampled4)
print(classification_report(y_train_resampled4, y_pred_train_xgb_sm))
print("Test Report:")
y_pred_test_xgb_sm = xgb_sm.predict(X_test)
print(classification_report(y_test, y_pred_test_xgb_sm))

SMOTE Resampling:
Training Report:
              precision    recall  f1-score   support

           0       0.90      0.93      0.91     20407
           1       0.69      0.89      0.78     20407
           2       0.75      0.57      0.65     20407
           3       0.78      0.72      0.74     20407

    accuracy                           0.78     81628
   macro avg       0.78      0.78      0.77     81628
weighted avg       0.78      0.78      0.77     81628

Test Report:
              precision    recall  f1-score   support

           0       0.62      0.60      0.61      1014
           1       0.68      0.84      0.75      5045
           2       0.32      0.12      0.17      1325
           3       0.37      0.24      0.29      1029

    accuracy                           0.62      8413
   macro avg       0.50      0.45      0.45      8413
weighted avg       0.58      0.62      0.59      8413

# logic

In [ ]:
smote = SMOTE(random_state=42)
X_train_resampled5, y_train_resampled5 = smote.fit_resample(X_train_scaled, y_train)
print("Before resampling:", Counter(y_train))
print("After resampling:", Counter(y_train_resampled5))

Before resampling: Counter({1: 20407, 2: 5115, 3: 4235, 0: 3894})
After resampling: Counter({0: 20407, 1: 20407, 2: 20407, 3: 20407})

In [ ]:
logicsm = LogisticRegression(random_state=42)
logicsm.fit(X_train_resampled5, y_train_resampled5)
print("Training Report:")
y_pred_train_logicsm = logicsm.predict(X_train_resampled5)
print(classification_report(y_train_resampled5, y_pred_train_logicsm))
print("Test Report:")
y_pred_test_logicsm = logicsm.predict(X_test_scaled)
print(classification_report(y_test, y_pred_test_logicsm))

Training Report:
              precision    recall  f1-score   support

           0       0.74      0.81      0.77     20407
           1       0.36      0.42      0.38     20407
           2       0.36      0.18      0.24     20407
           3       0.44      0.54      0.48     20407

    accuracy                           0.49     81628
   macro avg       0.47      0.49      0.47     81628
weighted avg       0.47      0.49      0.47     81628

Test Report:
              precision    recall  f1-score   support

           0       0.45      0.78      0.57      1014
           1       0.70      0.41      0.52      5045
           2       0.20      0.17      0.18      1325
           3       0.22      0.53      0.31      1029

    accuracy                           0.44      8413
   macro avg       0.39      0.48      0.40      8413
weighted avg       0.53      0.44      0.45      8413

# Adasyn

In [ ]:
from imblearn.over_sampling import ADASYN
adasyn = ADASYN(random_state=42)
X_train_resampled6, y_train_resampled6 = adasyn.fit_resample(X_train, y_train)
print("Before resampling:", Counter(y_train))
print("After resampling:", Counter(y_train_resampled6))

Before resampling: Counter({1: 20407, 2: 5115, 3: 4235, 0: 3894})
After resampling: Counter({3: 20750, 0: 20615, 2: 20526, 1: 20407})

In [ ]:
rc= RandomForestClassifier(random_state=42)
rc.fit(X_train_resampled6, y_train_resampled6)
y_pred_train_rf = rc.predict(X_train_resampled6 )
print("Training Report:")
print(classification_report(y_train_resampled6, y_pred_train_rf))
print()
y_pred_test_rf = rc.predict(X_test)
print("Test Report:")
print(classification_report(y_test, y_pred_test_rf))

Training Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     20615
           1       0.97      0.97      0.97     20407
           2       0.97      0.97      0.97     20526
           3       0.98      0.98      0.98     20750

    accuracy                           0.98     82298
   macro avg       0.98      0.98      0.98     82298
weighted avg       0.98      0.98      0.98     82298


Test Report:
              precision    recall  f1-score   support

           0       0.58      0.59      0.59      1014
           1       0.67      0.79      0.73      5045
           2       0.26      0.14      0.18      1325
           3       0.30      0.21      0.25      1029

    accuracy                           0.59      8413
   macro avg       0.46      0.43      0.44      8413
weighted avg       0.55      0.59      0.57      8413

# Xgb

In [ ]:
xga= xgb.XGBClassifier(random_state=42)
xga.fit(X_train_resampled6, y_train_resampled6)
print("Training Report:")
y_pred_train_xga = xga.predict(X_train_resampled6)
print(classification_report(y_train_resampled6, y_pred_train_xga))
print("Test Report:")
y_pred_test_xga = xga.predict(X_test)
print(classification_report(y_test, y_pred_test_xga))

Training Report:
              precision    recall  f1-score   support

           0       0.88      0.92      0.90     20615
           1       0.69      0.89      0.78     20407
           2       0.77      0.54      0.63     20526
           3       0.77      0.73      0.75     20750

    accuracy                           0.77     82298
   macro avg       0.77      0.77      0.76     82298
weighted avg       0.77      0.77      0.76     82298

Test Report:
              precision    recall  f1-score   support

           0       0.60      0.59      0.59      1014
           1       0.67      0.84      0.74      5045
           2       0.30      0.09      0.14      1325
           3       0.36      0.23      0.28      1029

    accuracy                           0.62      8413
   macro avg       0.48      0.44      0.44      8413
weighted avg       0.56      0.62      0.57      8413

# logic

In [ ]:
from imblearn.over_sampling import ADASYN
adasyn = ADASYN(random_state=42)
X_train_resampled7, y_train_resampled7 = adasyn.fit_resample(X_train_scaled, y_train)
print("Before resampling:", Counter(y_train))
print("After resampling:", Counter(y_train_resampled7))

Before resampling: Counter({1: 20407, 2: 5115, 3: 4235, 0: 3894})
After resampling: Counter({3: 20746, 2: 20570, 1: 20407, 0: 20125})

In [ ]:
logA=LogisticRegression(random_state=42)
logA.fit(X_train_resampled7, y_train_resampled7)
print("Training Report:")
y_pred_train_logA = logA.predict(X_train_resampled7)
print(classification_report(y_train_resampled7, y_pred_train_logA))
print("Test Report:")
y_pred_test_logA = logA.predict(X_test_scaled)
print(classification_report(y_test, y_pred_test_logA))

Training Report:
              precision    recall  f1-score   support

           0       0.69      0.79      0.73     20125
           1       0.34      0.41      0.37     20407
           2       0.35      0.12      0.18     20570
           3       0.42      0.55      0.47     20746

    accuracy                           0.46     81848
   macro avg       0.45      0.47      0.44     81848
weighted avg       0.45      0.46      0.44     81848

Test Report:
              precision    recall  f1-score   support

           0       0.43      0.82      0.56      1014
           1       0.71      0.40      0.51      5045
           2       0.19      0.12      0.15      1325
           3       0.21      0.58      0.31      1029

    accuracy                           0.43      8413
   macro avg       0.39      0.48      0.38      8413
weighted avg       0.53      0.43      0.44      8413

# Hybrid

In [ ]:
from imblearn.combine import SMOTETomek

smt = SMOTETomek(random_state=42)
X_res, y_res = smt.fit_resample(X_train, y_train)
print("Before resampling:", Counter(y_train))
print("After resampling:", Counter(y_res))

Before resampling: Counter({1: 20407, 2: 5115, 3: 4235, 0: 3894})
After resampling: Counter({0: 20355, 3: 20273, 1: 20241, 2: 20219})

In [ ]:
rc= RandomForestClassifier(random_state=42)
rc.fit(X_res, y_res)
y_pred_train_rf = rc.predict(X_res)
print("Training Report:")
print(classification_report(y_res, y_pred_train_rf))
print()
y_pred_test_rf = rc.predict(X_test)
print("Test Report:")
print(classification_report(y_test, y_pred_test_rf))

Training Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     20355
           1       0.97      0.96      0.97     20241
           2       0.96      0.97      0.97     20219
           3       0.98      0.98      0.98     20273

    accuracy                           0.98     81088
   macro avg       0.98      0.98      0.98     81088
weighted avg       0.98      0.98      0.98     81088


Test Report:
              precision    recall  f1-score   support

           0       0.59      0.61      0.60      1014
           1       0.67      0.79      0.73      5045
           2       0.26      0.14      0.18      1325
           3       0.32      0.23      0.27      1029

    accuracy                           0.60      8413
   macro avg       0.46      0.44      0.44      8413
weighted avg       0.56      0.60      0.57      8413

#xgb

In [ ]:
print("SMOTETomek Resampling:")
xgh=xgb.XGBClassifier(random_state=42)
xgh.fit(X_res, y_res)
print("Training Report:")
y_pred_train_xgh = xgh.predict(X_res)
print(classification_report(y_res, y_pred_train_xgh))
print("Test Report:")
y_pred_test_xgh = xgh.predict(X_test)
print(classification_report(y_test, y_pred_test_xgh))

SMOTETomek Resampling:
Training Report:
              precision    recall  f1-score   support

           0       0.90      0.92      0.91     20355
           1       0.69      0.89      0.78     20241
           2       0.76      0.58      0.66     20219
           3       0.77      0.72      0.75     20273

    accuracy                           0.78     81088
   macro avg       0.78      0.78      0.77     81088
weighted avg       0.78      0.78      0.77     81088

Test Report:
              precision    recall  f1-score   support

           0       0.62      0.59      0.60      1014
           1       0.68      0.84      0.75      5045
           2       0.32      0.12      0.17      1325
           3       0.36      0.24      0.29      1029

    accuracy                           0.62      8413
   macro avg       0.49      0.45      0.45      8413
weighted avg       0.57      0.62      0.58      8413

# logic

In [ ]:
smt = SMOTETomek(random_state=42)
X_res1, y_res1 = smt.fit_resample(X_train_scaled, y_train)
print("Before resampling:", Counter(y_train))
print("After resampling:", Counter(y_res1))

Before resampling: Counter({1: 20407, 2: 5115, 3: 4235, 0: 3894})
After resampling: Counter({0: 20155, 1: 19692, 3: 19673, 2: 19536})

In [ ]:
logih=LogisticRegression(random_state=42)
logih.fit(X_res1, y_res1)
print("Training Report:")
y_pred_train_logih = logih.predict(X_res1)
print(classification_report(y_res1, y_pred_train_logih))
print("Test Report:")
y_pred_test_logih = logih.predict(X_test_scaled)
print(classification_report(y_test, y_pred_test_logih))

Training Report:
              precision    recall  f1-score   support

           0       0.74      0.82      0.78     20155
           1       0.36      0.43      0.39     19692
           2       0.36      0.16      0.22     19536
           3       0.44      0.55      0.49     19673

    accuracy                           0.49     79056
   macro avg       0.48      0.49      0.47     79056
weighted avg       0.48      0.49      0.47     79056

Test Report:
              precision    recall  f1-score   support

           0       0.45      0.78      0.57      1014
           1       0.70      0.43      0.53      5045
           2       0.20      0.16      0.18      1325
           3       0.22      0.54      0.31      1029

    accuracy                           0.44      8413
   macro avg       0.39      0.48      0.40      8413
weighted avg       0.53      0.44      0.45      8413

# SmoteEN

In [ ]:
from imblearn.combine import SMOTEENN

sme = SMOTEENN(random_state=42)
X_res2, y_res2 = sme.fit_resample(X_train, y_train)
print("Before resampling:", Counter(y_train))
print("After resampling:", Counter(y_res2))

Before resampling: Counter({1: 20407, 2: 5115, 3: 4235, 0: 3894})
After resampling: Counter({0: 19300, 3: 16906, 2: 14974, 1: 4367})

In [ ]:
print("SMOTEENN Resampling:")
xgbh1 = xgb.XGBClassifier(random_state=42)
xgbh1.fit(X_res2, y_res2)
print("Training Report:")
print(classification_report(y_res2, xgbh1.predict(X_res2)))
print("Test Report:")
print(classification_report(y_test, xgbh1.predict(X_test)))

SMOTEENN Resampling:
Training Report:
              precision    recall  f1-score   support

           0       0.95      0.98      0.97     19300
           1       0.85      0.81      0.83      4367
           2       0.82      0.76      0.79     14974
           3       0.84      0.87      0.85     16906

    accuracy                           0.87     55547
   macro avg       0.86      0.86      0.86     55547
weighted avg       0.87      0.87      0.87     55547

Test Report:
              precision    recall  f1-score   support

           0       0.42      0.87      0.56      1014
           1       0.79      0.32      0.46      5045
           2       0.22      0.38      0.28      1325
           3       0.26      0.50      0.34      1029

    accuracy                           0.42      8413
   macro avg       0.42      0.52      0.41      8413
weighted avg       0.59      0.42      0.43      8413

In [ ]:
sme = SMOTEENN(random_state=42)
X_res3, y_res3 = sme.fit_resample(X_train_scaled, y_train)
print("Before resampling:", Counter(y_train))
print("After resampling:", Counter(y_res3))

Before resampling: Counter({1: 20407, 2: 5115, 3: 4235, 0: 3894})
After resampling: Counter({0: 18158, 3: 11219, 2: 8582, 1: 4657})

In [ ]:
logh2=LogisticRegression(random_state=42)
logh2.fit(X_res3, y_res3)
print("Training Report:")
y_pred_train_logh2 = logh2.predict(X_res3)
print(classification_report(y_res3, y_pred_train_logh2))
print("Test Report:")
y_pred_test_logh2 = logh2.predict(X_test_scaled)
print(classification_report(y_test, y_pred_test_logh2))

Training Report:
              precision    recall  f1-score   support

           0       0.84      0.92      0.87     18158
           1       0.51      0.49      0.50      4657
           2       0.35      0.14      0.20      8582
           3       0.55      0.72      0.62     11219

    accuracy                           0.66     42616
   macro avg       0.56      0.57      0.55     42616
weighted avg       0.63      0.66      0.63     42616

Test Report:
              precision    recall  f1-score   support

           0       0.39      0.87      0.54      1014
           1       0.72      0.32      0.45      5045
           2       0.16      0.08      0.11      1325
           3       0.21      0.65      0.32      1029

    accuracy                           0.39      8413
   macro avg       0.37      0.48      0.35      8413
weighted avg       0.53      0.39      0.39      8413